name: Busca Diaria IPTV Censys

on:
  workflow_dispatch: # Permite rodar manualmente no botão "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: '24' # Versão recomendada pelo GitHub agora

      - name: Install dependencies
        run: npm install axios telegraf

      - name: Rodar Script Node
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
          CENSYS_TOKEN: ${{ secrets.CENSYS_TOKEN }}
        run: node index.js
